apiVersion: v1
kind: Pod
metadata:
  name: hw4-resources
  labels:
    app: test
spec:
  containers:
    - image: reconrus/made-ml-prod-hw2:v1
      name: hw4
      ports:
        - containerPort: 5000
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "1000m"